#!/usr/bin/env python3
"""
Setup script for PathwayLens 2.0
"""

from setuptools import setup, find_packages

setup(
    name="pathwaylens",
    version="2.0.0",
    description="Next-generation computational biology platform for multi-omics pathway analysis",
    author="PathwayLens Team",
    author_email="pathwaylens@example.com",
    packages=find_packages(),
    python_requires=">=3.8",
    install_requires=[
        "typer>=0.9.0",
        "rich>=13.0.0",
        "click>=8.0.0",
        "pandas>=2.0.0",
        "numpy>=1.24.0",
        "scipy>=1.10.0",
        "matplotlib>=3.7.0",
        "seaborn>=0.12.0",
        "plotly>=5.15.0",
        "requests>=2.31.0",
        "aiohttp>=3.8.0",
        "fastapi>=0.100.0",
        "uvicorn>=0.23.0",
        "pydantic>=2.0.0",
        "pyyaml>=6.0",
        "loguru>=0.7.0",
        "biopython>=1.79",
        "mygene>=3.2.2",
        "openpyxl>=3.1.0",
        "xlrd>=2.0.0",
        "celery>=5.3.0",
        "redis>=4.6.0",
        "sqlalchemy>=2.0.0",
        "alembic>=1.12.0",
        "psycopg2-binary>=2.9.0",
        "python-multipart>=0.0.6",
        "python-jose>=3.3.0",
        "passlib>=1.7.4",
        "bcrypt>=4.0.0",
        "httpx>=0.24.0",
        "tenacity>=8.2.0",
        "cachetools>=5.3.0",
        "h5py>=3.9.0",
        "zarr>=2.16.0",
        "networkx>=3.1.0",
        "scikit-learn>=1.3.0",
        "statsmodels>=0.14.0",
        "gseapy>=1.0.0",
        "enrichr>=3.2.0",
        "gprofiler-official>=1.0.0",
        "pyensembl>=2.2.0",
        "pybiomart>=0.2.0",
        "bioservices>=1.11.0",
        "goatools>=1.3.0",
    ],
    entry_points={
        'console_scripts': [
            'pathwaylens=pathwaylens_cli.main:app',
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Bio-Informatics",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)